import React from 'react';

interface LegalPageProps {
    page: 'privacy' | 'terms';
    onClose: () => void;
}

export function LegalPage({ page, onClose }: LegalPageProps) {
    return (
        <div className="fixed inset-0 z-[300] bg-altar-deep text-altar-text overflow-y-auto">
            {/* Header */}
            <div className="sticky top-0 z-10 bg-altar-deep/95 backdrop-blur-xl border-b border-white/5">
                <div className="flex items-center justify-between px-4 py-3 max-w-[600px] mx-auto">
                    <h1 className="font-display text-sm tracking-[3px] text-altar-gold uppercase">
                        {page === 'privacy' ? 'Privacy Policy' : 'Terms of Service'}
                    </h1>
                    <button
                        onClick={onClose}
                        className="w-8 h-8 rounded-full glass flex items-center justify-center text-white/60 hover:text-white transition-colors"
                    >
                        ✕
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-[600px] mx-auto px-5 py-6 text-sm leading-relaxed text-altar-muted">
                {page === 'privacy' ? <PrivacyContent /> : <TermsContent />}
            </div>
        </div>
    );
}

function PrivacyContent() {
    return (
        <div className="space-y-5">
            <p className="text-[10px] text-altar-muted/50">Last updated: March 7, 2026</p>

            <Section title="1. Introduction">
                <p>
                    Arcana Whisper ("we", "our", "the App") is committed to protecting your privacy.
                    This Privacy Policy explains what data we collect, how we use it, and your rights.
                </p>
            </Section>

            <Section title="2. Data We Collect">
                <p className="font-medium text-altar-text mb-2">Information you provide:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                    <li><strong>Name or alias</strong> — Used to personalize your readings</li>
                    <li><strong>Date of birth</strong> — Used for natal chart, zodiac, and numerology calculations</li>
                    <li><strong>Birth time</strong> (optional) — Used for accurate Rising sign calculation</li>
                    <li><strong>Birth city/location</strong> (optional) — Used for astronomical coordinate-based calculations</li>
                    <li><strong>Reading history</strong> — Your tarot readings, journal entries, and questions</li>
                </ul>

                <p className="font-medium text-altar-text mb-2 mt-4">Information generated by the App:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>Natal chart calculations (Sun, Moon, Rising signs)</li>
                    <li>Numerology life path and expression numbers</li>
                    <li>Personalized interpretations of your readings</li>
                </ul>
            </Section>

            <Section title="3. How We Use Your Data">
                <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>To generate personalized tarot readings and astrological charts</li>
                    <li>To provide personalized interpretations via a third-party service (see Section 5)</li>
                    <li>To maintain your reading history and preferences</li>
                    <li>To calculate your natal chart, numerology profile, and horoscope</li>
                </ul>
            </Section>

            <Section title="4. Data Storage">
                <p>
                    All personal data is stored <strong>locally on your device</strong> using the device's
                    built-in storage. We do not maintain servers that store your personal information.
                    Your data never leaves your device except when sent to a third-party service for generating
                    interpretations (see Section 5).
                </p>
            </Section>

            <Section title="5. Third-Party Interpretation Service">
                <p>
                    Arcana Whisper uses <strong>OpenRouter</strong>, a third-party service, to generate
                    personalized interpretations of your tarot readings and natal chart insights. When you
                    request an interpretation, the following data may be sent to OpenRouter:
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
                    <li>Your tarot card selections and spread layout</li>
                    <li>Your zodiac sign information</li>
                    <li>Your question or theme for the reading</li>
                    <li>Your birth data (date, time, location) for natal chart interpretations</li>
                </ul>
                <p className="mt-2">
                    OpenRouter processes this data solely to generate your personalized reading.
                    Please review{' '}
                    <a
                        href="https://openrouter.ai/privacy"
                        className="text-altar-gold underline"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        OpenRouter's Privacy Policy
                    </a>{' '}
                    for their data handling practices.
                </p>
            </Section>

            <Section title="6. Data Sharing">
                <p>
                    We do not sell, trade, or share your personal data with third parties for marketing
                    purposes. Data is only shared with OpenRouter as described in Section 5, and only
                    when you actively request a personalized interpretation.
                </p>
            </Section>

            <Section title="7. Your Rights">
                <p>You have the right to:</p>
                <ul className="list-disc list-inside space-y-1 ml-2 mt-1">
                    <li><strong>View your data</strong> — All your data is visible within the app</li>
                    <li><strong>Delete your data</strong> — Use the "Delete My Account & Data" option in Profile → Settings</li>
                    <li><strong>Opt out of personalized features</strong> — You can use the app's tarot, astrology, and numerology features without requesting personalized interpretations</li>
                </ul>
            </Section>

            <Section title="8. Children's Privacy">
                <p>
                    Arcana Whisper is not intended for children under 13. We do not knowingly collect
                    personal information from children under 13. If you believe your child has provided
                    us with personal information, please contact us to have it deleted.
                </p>
            </Section>

            <Section title="9. California Residents (CCPA)">
                <p>
                    If you are a California resident, you have the right to request deletion of your
                    personal information. Since all data is stored locally on your device, you can
                    delete it at any time through the app's "Delete My Account & Data" feature.
                </p>
            </Section>

            <Section title="10. Changes to This Policy">
                <p>
                    We may update this Privacy Policy from time to time. Changes will be reflected
                    within the app. Continued use of the app constitutes acceptance of the updated policy.
                </p>
            </Section>

            <Section title="11. Contact">
                <p>
                    For privacy-related questions, contact us at:{' '}
                    <span className="text-altar-gold">privacy@arcanawhisper.com</span>
                </p>
            </Section>
        </div>
    );
}

function TermsContent() {
    return (
        <div className="space-y-5">
            <p className="text-[10px] text-altar-muted/50">Last updated: March 7, 2026</p>

            <Section title="1. Acceptance of Terms">
                <p>
                    By downloading, installing, or using Arcana Whisper ("the App"), you agree to be
                    bound by these Terms of Service. If you do not agree, do not use the App.
                </p>
            </Section>

            <Section title="2. Description of Service">
                <p>
                    Arcana Whisper is an entertainment and self-reflection app that provides tarot card
                    readings, astrological charts, numerology calculations, horoscopes, and personalized
                    interpretations. The App is intended for <strong>entertainment and personal insight
                        purposes only</strong>.
                </p>
            </Section>

            <Section title="3. Disclaimer — Not Professional Advice">
                <p className="text-amber-300/80 font-medium">
                    ⚠️ Arcana Whisper does NOT provide medical, psychological, financial, legal, or
                    professional advice of any kind. Readings and interpretations are for entertainment
                    and self-reflection purposes only. Do not make important life decisions based solely
                    on app readings. Always consult qualified professionals for health, financial, legal,
                    or psychological matters.
                </p>
            </Section>

            <Section title="4. Subscriptions & In-App Purchases">
                <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>Premium features are available via auto-renewable subscriptions</li>
                    <li>Payment is charged to your Apple ID account at confirmation of purchase</li>
                    <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period</li>
                    <li>Your account will be charged for renewal within 24 hours prior to the end of the current period</li>
                    <li>You can manage and cancel subscriptions in your App Store account settings</li>
                    <li>No refunds for partial subscription periods</li>
                </ul>
            </Section>

            <Section title="5. User Conduct">
                <p>
                    You agree not to misuse the App, attempt to reverse-engineer it, or use it for
                    any unlawful purpose. The App is provided for personal, non-commercial use.
                </p>
            </Section>

            <Section title="6. Intellectual Property">
                <p>
                    All content, designs, and features within Arcana Whisper are the intellectual
                    property of Arcana Whisper and are protected by applicable copyright and trademark
                    laws. You may not reproduce, distribute, or create derivative works without
                    our written permission.
                </p>
            </Section>

            <Section title="7. Limitation of Liability">
                <p>
                    Arcana Whisper and its creators are not liable for any decisions made based on
                    app readings, loss of data, or any indirect, incidental, or consequential damages
                    arising from the use of the App. The App is provided "AS IS" without warranties
                    of any kind.
                </p>
            </Section>

            <Section title="8. Data Deletion">
                <p>
                    You may delete all your personal data at any time through the "Delete My Account & Data"
                    option in Profile → Settings. This action is permanent and cannot be undone.
                </p>
            </Section>

            <Section title="9. Termination">
                <p>
                    We reserve the right to terminate or suspend access to the App at any time,
                    without notice, for conduct that we believe violates these Terms or is harmful
                    to other users or third parties.
                </p>
            </Section>

            <Section title="10. Changes to Terms">
                <p>
                    We may modify these Terms at any time. Continued use of the App after changes
                    constitutes acceptance of the new Terms.
                </p>
            </Section>

            <Section title="11. Contact">
                <p>
                    For questions about these Terms, contact us at:{' '}
                    <span className="text-altar-gold">support@arcanawhisper.com</span>
                </p>
            </Section>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div>
            <h2 className="font-display text-xs text-altar-gold tracking-[2px] uppercase mb-2">{title}</h2>
            <div className="text-xs text-altar-muted leading-relaxed space-y-2">{children}</div>
        </div>
    );
}
